// Unicode blocks
export type UnicodeBlock = {
    start: number;
    end: number;
    name: string;
    wiki: string | null;
    color: string;
}

const undefinedUnicodeBlock: UnicodeBlock = { start: -1, end: -2, name: "Undefined", wiki: null, color: "#808080"};
const unicodeBlocks: UnicodeBlock[] = [
    { start: 0x0000, end: 0x007F, name: "Basic Latin", wiki: "https://en.wikipedia.org//wiki/Basic_Latin_(Unicode_block)", color: "#dcac15"},
    { start: 0x0080, end: 0x00FF, name: "Latin-1 Supplement", wiki: "https://en.wikipedia.org//wiki/Latin-1_Supplement", color: "#19d2a2"},
    { start: 0x0100, end: 0x017F, name: "Latin Extended-A", wiki: "https://en.wikipedia.org//wiki/Latin_Extended-A", color: "#e8912b"},
    { start: 0x0180, end: 0x024F, name: "Latin Extended-B", wiki: "https://en.wikipedia.org//wiki/Latin_Extended-B", color: "#05dba5"},
    { start: 0x0250, end: 0x02AF, name: "IPA Extensions", wiki: "https://en.wikipedia.org//wiki/IPA_Extensions", color: "#179b5c"},
    { start: 0x02B0, end: 0x02FF, name: "Spacing Modifier Letters", wiki: "https://en.wikipedia.org//wiki/Spacing_Modifier_Letters", color: "#9c4515"},
    { start: 0x0300, end: 0x036F, name: "Combining Diacritical Marks", wiki: "https://en.wikipedia.org//wiki/Combining_Diacritical_Marks", color: "#810aa7"},
    { start: 0x0370, end: 0x03FF, name: "Greek and Coptic", wiki: "https://en.wikipedia.org//wiki/Greek_and_Coptic", color: "#342300"},
    { start: 0x0400, end: 0x04FF, name: "Cyrillic", wiki: "https://en.wikipedia.org//wiki/Cyrillic_(Unicode_block)", color: "#b76422"},
    { start: 0x0500, end: 0x052F, name: "Cyrillic Supplement", wiki: "https://en.wikipedia.org//wiki/Cyrillic_Supplement", color: "#52a93a"},
    { start: 0x0530, end: 0x058F, name: "Armenian", wiki: "https://en.wikipedia.org//wiki/Armenian_(Unicode_block)", color: "#05df12"},
    { start: 0x0590, end: 0x05FF, name: "Hebrew", wiki: "https://en.wikipedia.org//wiki/Hebrew_(Unicode_block)", color: "#7da998"},
    { start: 0x0600, end: 0x06FF, name: "Arabic", wiki: "https://en.wikipedia.org//wiki/Arabic_(Unicode_block)", color: "#53b51d"},
    { start: 0x0700, end: 0x074F, name: "Syriac", wiki: "https://en.wikipedia.org//wiki/Syriac_(Unicode_block)", color: "#ece8c8"},
    { start: 0x0750, end: 0x077F, name: "Arabic Supplement", wiki: "https://en.wikipedia.org//wiki/Arabic_Supplement", color: "#4901bf"},
    { start: 0x0780, end: 0x07BF, name: "Thaana", wiki: "https://en.wikipedia.org//wiki/Thaana_(Unicode_block)", color: "#d4790b"},
    { start: 0x07C0, end: 0x07FF, name: "NKo", wiki: "https://en.wikipedia.org//wiki/NKo_(Unicode_block)", color: "#d334e9"},
    { start: 0x0800, end: 0x083F, name: "Samaritan", wiki: "https://en.wikipedia.org//wiki/Samaritan_(Unicode_block)", color: "#e2da83"},
    { start: 0x0840, end: 0x085F, name: "Mandaic", wiki: "https://en.wikipedia.org//wiki/Mandaic_(Unicode_block)", color: "#bf82dc"},
    { start: 0x0860, end: 0x086F, name: "Syriac Supplement", wiki: "https://en.wikipedia.org//wiki/Syriac_Supplement", color: "#8ed357"},
    { start: 0x0870, end: 0x089F, name: "Arabic Extended-B", wiki: "https://en.wikipedia.org//wiki/Arabic_Extended-B", color: "#6ac552"},
    { start: 0x08A0, end: 0x08FF, name: "Arabic Extended-A", wiki: "https://en.wikipedia.org//wiki/Arabic_Extended-A", color: "#364522"},
    { start: 0x0900, end: 0x097F, name: "Devanagari", wiki: "https://en.wikipedia.org//wiki/Devanagari_(Unicode_block)", color: "#bc6fa8"},
    { start: 0x0980, end: 0x09FF, name: "Bengali", wiki: "https://en.wikipedia.org//wiki/Bengali_(Unicode_block)", color: "#103f0f"},
    { start: 0x0A00, end: 0x0A7F, name: "Gurmukhi", wiki: "https://en.wikipedia.org//wiki/Gurmukhi_(Unicode_block)", color: "#d98887"},
    { start: 0x0A80, end: 0x0AFF, name: "Gujarati", wiki: "https://en.wikipedia.org//wiki/Gujarati_(Unicode_block)", color: "#4ec701"},
    { start: 0x0B00, end: 0x0B7F, name: "Oriya", wiki: "https://en.wikipedia.org//wiki/Oriya_(Unicode_block)", color: "#aaa345"},
    { start: 0x0B80, end: 0x0BFF, name: "Tamil", wiki: "https://en.wikipedia.org//wiki/Tamil_(Unicode_block)", color: "#d05fd7"},
    { start: 0x0C00, end: 0x0C7F, name: "Telugu", wiki: "https://en.wikipedia.org//wiki/Telugu_(Unicode_block)", color: "#6db509"},
    { start: 0x0C80, end: 0x0CFF, name: "Kannada", wiki: "https://en.wikipedia.org//wiki/Kannada_(Unicode_block)", color: "#e363da"},
    { start: 0x0D00, end: 0x0D7F, name: "Malayalam", wiki: "https://en.wikipedia.org//wiki/Malayalam_(Unicode_block)", color: "#2066e0"},
    { start: 0x0D80, end: 0x0DFF, name: "Sinhala", wiki: "https://en.wikipedia.org//wiki/Sinhala_(Unicode_block)", color: "#f5f46a"},
    { start: 0x0E00, end: 0x0E7F, name: "Thai", wiki: "https://en.wikipedia.org//wiki/Thai_(Unicode_block)", color: "#33bc87"},
    { start: 0x0E80, end: 0x0EFF, name: "Lao", wiki: "https://en.wikipedia.org//wiki/Lao_(Unicode_block)", color: "#68a890"},
    { start: 0x0F00, end: 0x0FFF, name: "Tibetan", wiki: "https://en.wikipedia.org//wiki/Tibetan_(Unicode_block)", color: "#959bbb"},
    { start: 0x1000, end: 0x109F, name: "Myanmar", wiki: "https://en.wikipedia.org//wiki/Myanmar_(Unicode_block)", color: "#c6506c"},
    { start: 0x10A0, end: 0x10FF, name: "Georgian", wiki: "https://en.wikipedia.org//wiki/Georgian_(Unicode_block)", color: "#56f1b8"},
    { start: 0x1100, end: 0x11FF, name: "Hangul Jamo", wiki: "https://en.wikipedia.org//wiki/Hangul_Jamo_(Unicode_block)", color: "#203018"},
    { start: 0x1200, end: 0x137F, name: "Ethiopic", wiki: "https://en.wikipedia.org//wiki/Ethiopic_(Unicode_block)", color: "#0a037d"},
    { start: 0x1380, end: 0x139F, name: "Ethiopic Supplement", wiki: "https://en.wikipedia.org//wiki/Ethiopic_Supplement", color: "#71afcb"},
    { start: 0x13A0, end: 0x13FF, name: "Cherokee", wiki: "https://en.wikipedia.org//wiki/Cherokee_(Unicode_block)", color: "#c4d516"},
    { start: 0x1400, end: 0x167F, name: "Unified Canadian Aboriginal Syllabics", wiki: "https://en.wikipedia.org//wiki/Unified_Canadian_Aboriginal_Syllabics_(Unicode_block)", color: "#5cf3c9"},
    { start: 0x1680, end: 0x169F, name: "Ogham", wiki: "https://en.wikipedia.org//wiki/Ogham_(Unicode_block)", color: "#9129c0"},
    { start: 0x16A0, end: 0x16FF, name: "Runic", wiki: "https://en.wikipedia.org//wiki/Runic_(Unicode_block)", color: "#b39c95"},
    { start: 0x1700, end: 0x171F, name: "Tagalog", wiki: "https://en.wikipedia.org//wiki/Tagalog_(Unicode_block)", color: "#29a4ab"},
    { start: 0x1720, end: 0x173F, name: "Hanunoo", wiki: "https://en.wikipedia.org//wiki/Hanunoo_(Unicode_block)", color: "#d14217"},
    { start: 0x1740, end: 0x175F, name: "Buhid", wiki: "https://en.wikipedia.org//wiki/Buhid_(Unicode_block)", color: "#0642a3"},
    { start: 0x1760, end: 0x177F, name: "Tagbanwa", wiki: "https://en.wikipedia.org//wiki/Tagbanwa_(Unicode_block)", color: "#e5515d"},
    { start: 0x1780, end: 0x17FF, name: "Khmer", wiki: "https://en.wikipedia.org//wiki/Khmer_(Unicode_block)", color: "#a0c2e4"},
    { start: 0x1800, end: 0x18AF, name: "Mongolian", wiki: "https://en.wikipedia.org//wiki/Mongolian_(Unicode_block)", color: "#ae7b6f"},
    { start: 0x18B0, end: 0x18FF, name: "Unified Canadian Aboriginal Syllabics Extended", wiki: "https://en.wikipedia.org//wiki/Unified_Canadian_Aboriginal_Syllabics_Extended", color: "#e36a25"},
    { start: 0x1900, end: 0x194F, name: "Limbu", wiki: "https://en.wikipedia.org//wiki/Limbu_(Unicode_block)", color: "#380bc1"},
    { start: 0x1950, end: 0x197F, name: "Tai Le", wiki: "https://en.wikipedia.org//wiki/Tai_Le_(Unicode_block)", color: "#6b64de"},
    { start: 0x1980, end: 0x19DF, name: "New Tai Lue", wiki: "https://en.wikipedia.org//wiki/New_Tai_Lue_(Unicode_block)", color: "#58e330"},
    { start: 0x19E0, end: 0x19FF, name: "Khmer Symbols", wiki: "https://en.wikipedia.org//wiki/Khmer_Symbols", color: "#73a8ea"},
    { start: 0x1A00, end: 0x1A1F, name: "Buginese", wiki: "https://en.wikipedia.org//wiki/Buginese_(Unicode_block)", color: "#f5d317"},
    { start: 0x1A20, end: 0x1AAF, name: "Tai Tham", wiki: "https://en.wikipedia.org//wiki/Tai_Tham_(Unicode_block)", color: "#81ca41"},
    { start: 0x1AB0, end: 0x1AFF, name: "Combining Diacritical Marks Extended", wiki: "https://en.wikipedia.org//wiki/Combining_Diacritical_Marks_Extended", color: "#810fc2"},
    { start: 0x1B00, end: 0x1B7F, name: "Balinese", wiki: "https://en.wikipedia.org//wiki/Balinese_(Unicode_block)", color: "#7621b3"},
    { start: 0x1B80, end: 0x1BBF, name: "Sundanese", wiki: "https://en.wikipedia.org//wiki/Sundanese_(Unicode_block)", color: "#4afc62"},
    { start: 0x1BC0, end: 0x1BFF, name: "Batak", wiki: "https://en.wikipedia.org//wiki/Batak_(Unicode_block)", color: "#a4a2d4"},
    { start: 0x1C00, end: 0x1C4F, name: "Lepcha", wiki: "https://en.wikipedia.org//wiki/Lepcha_(Unicode_block)", color: "#d9131a"},
    { start: 0x1C50, end: 0x1C7F, name: "Ol Chiki", wiki: "https://en.wikipedia.org//wiki/Ol_Chiki_(Unicode_block)", color: "#c8bb1f"},
    { start: 0x1C80, end: 0x1C8F, name: "Cyrillic Extended-C", wiki: "https://en.wikipedia.org//wiki/Cyrillic_Extended-C", color: "#d44fe5"},
    { start: 0x1C90, end: 0x1CBF, name: "Georgian Extended", wiki: "https://en.wikipedia.org//wiki/Georgian_Extended", color: "#fa867d"},
    { start: 0x1CC0, end: 0x1CCF, name: "Sundanese Supplement", wiki: "https://en.wikipedia.org//wiki/Sundanese_Supplement", color: "#d74fc4"},
    { start: 0x1CD0, end: 0x1CFF, name: "Vedic Extensions", wiki: "https://en.wikipedia.org//wiki/Vedic_Extensions", color: "#1ac3e1"},
    { start: 0x1D00, end: 0x1D7F, name: "Phonetic Extensions", wiki: "https://en.wikipedia.org//wiki/Phonetic_Extensions", color: "#e19bcd"},
    { start: 0x1D80, end: 0x1DBF, name: "Phonetic Extensions Supplement", wiki: "https://en.wikipedia.org//wiki/Phonetic_Extensions_Supplement", color: "#ad3037"},
    { start: 0x1DC0, end: 0x1DFF, name: "Combining Diacritical Marks Supplement", wiki: "https://en.wikipedia.org//wiki/Combining_Diacritical_Marks_Supplement", color: "#4ccc65"},
    { start: 0x1E00, end: 0x1EFF, name: "Latin Extended Additional", wiki: "https://en.wikipedia.org//wiki/Latin_Extended_Additional", color: "#89b3eb"},
    { start: 0x1F00, end: 0x1FFF, name: "Greek Extended", wiki: "https://en.wikipedia.org//wiki/Greek_Extended", color: "#81918e"},
    { start: 0x2000, end: 0x206F, name: "General Punctuation", wiki: "https://en.wikipedia.org//wiki/General_Punctuation", color: "#e5211a"},
    { start: 0x2070, end: 0x209F, name: "Superscripts and Subscripts", wiki: "https://en.wikipedia.org//wiki/Superscripts_and_Subscripts_(Unicode_block)", color: "#7ac977"},
    { start: 0x20A0, end: 0x20CF, name: "Currency Symbols", wiki: "https://en.wikipedia.org//wiki/Currency_Symbols_(Unicode_block)", color: "#2401a5"},
    { start: 0x20D0, end: 0x20FF, name: "Combining Diacritical Marks for Symbols", wiki: "https://en.wikipedia.org//wiki/Combining_Diacritical_Marks_for_Symbols", color: "#7dea12"},
    { start: 0x2100, end: 0x214F, name: "Letterlike Symbols", wiki: "https://en.wikipedia.org//wiki/Letterlike_Symbols", color: "#0d2a17"},
    { start: 0x2150, end: 0x218F, name: "Number Forms", wiki: "https://en.wikipedia.org//wiki/Number_Forms", color: "#348ebb"},
    { start: 0x2190, end: 0x21FF, name: "Arrows", wiki: "https://en.wikipedia.org//wiki/Arrows_(Unicode_block)", color: "#1c4a22"},
    { start: 0x2200, end: 0x22FF, name: "Mathematical Operators", wiki: "https://en.wikipedia.org//wiki/Mathematical_Operators_(Unicode_block)", color: "#5cd074"},
    { start: 0x2300, end: 0x23FF, name: "Miscellaneous Technical", wiki: "https://en.wikipedia.org//wiki/Miscellaneous_Technical", color: "#643408"},
    { start: 0x2400, end: 0x243F, name: "Control Pictures", wiki: "https://en.wikipedia.org//wiki/Control_Pictures", color: "#547522"},
    { start: 0x2440, end: 0x245F, name: "Optical Character Recognition", wiki: "https://en.wikipedia.org//wiki/Optical_Character_Recognition_(Unicode_block)", color: "#a04026"},
    { start: 0x2460, end: 0x24FF, name: "Enclosed Alphanumerics", wiki: "https://en.wikipedia.org//wiki/Enclosed_Alphanumerics", color: "#8a7202"},
    { start: 0x2500, end: 0x257F, name: "Box Drawing", wiki: "https://en.wikipedia.org//wiki/Box_Drawing", color: "#249e30"},
    { start: 0x2580, end: 0x259F, name: "Block Elements", wiki: "https://en.wikipedia.org//wiki/Block_Elements", color: "#6b86d8"},
    { start: 0x25A0, end: 0x25FF, name: "Geometric Shapes", wiki: "https://en.wikipedia.org//wiki/Geometric_Shapes_(Unicode_block)", color: "#034881"},
    { start: 0x2600, end: 0x26FF, name: "Miscellaneous Symbols", wiki: "https://en.wikipedia.org//wiki/Miscellaneous_Symbols", color: "#edcdee"},
    { start: 0x2700, end: 0x27BF, name: "Dingbats", wiki: "https://en.wikipedia.org//wiki/Dingbats_(Unicode_block)", color: "#056f31"},
    { start: 0x27C0, end: 0x27EF, name: "Miscellaneous Mathematical Symbols-A", wiki: "https://en.wikipedia.org//wiki/Miscellaneous_Mathematical_Symbols-A", color: "#13f669"},
    { start: 0x27F0, end: 0x27FF, name: "Supplemental Arrows-A", wiki: "https://en.wikipedia.org//wiki/Supplemental_Arrows-A", color: "#125a5b"},
    { start: 0x2800, end: 0x28FF, name: "Braille Patterns", wiki: "https://en.wikipedia.org//wiki/Braille_Patterns", color: "#bd19ec"},
    { start: 0x2900, end: 0x297F, name: "Supplemental Arrows-B", wiki: "https://en.wikipedia.org//wiki/Supplemental_Arrows-B", color: "#c16172"},
    { start: 0x2980, end: 0x29FF, name: "Miscellaneous Mathematical Symbols-B", wiki: "https://en.wikipedia.org//wiki/Miscellaneous_Mathematical_Symbols-B", color: "#be553c"},
    { start: 0x2A00, end: 0x2AFF, name: "Supplemental Mathematical Operators", wiki: "https://en.wikipedia.org//wiki/Supplemental_Mathematical_Operators", color: "#84d169"},
    { start: 0x2B00, end: 0x2BFF, name: "Miscellaneous Symbols and Arrows", wiki: "https://en.wikipedia.org//wiki/Miscellaneous_Symbols_and_Arrows", color: "#746ceb"},
    { start: 0x2C00, end: 0x2C5F, name: "Glagolitic", wiki: "https://en.wikipedia.org//wiki/Glagolitic_(Unicode_block)", color: "#e2a6c7"},
    { start: 0x2C60, end: 0x2C7F, name: "Latin Extended-C", wiki: "https://en.wikipedia.org//wiki/Latin_Extended-C", color: "#dadf7f"},
    { start: 0x2C80, end: 0x2CFF, name: "Coptic", wiki: "https://en.wikipedia.org//wiki/Coptic_(Unicode_block)", color: "#365f70"},
    { start: 0x2D00, end: 0x2D2F, name: "Georgian Supplement", wiki: "https://en.wikipedia.org//wiki/Georgian_Supplement", color: "#394f2c"},
    { start: 0x2D30, end: 0x2D7F, name: "Tifinagh", wiki: "https://en.wikipedia.org//wiki/Tifinagh_(Unicode_block)", color: "#132436"},
    { start: 0x2D80, end: 0x2DDF, name: "Ethiopic Extended", wiki: "https://en.wikipedia.org//wiki/Ethiopic_Extended", color: "#bd5c44"},
    { start: 0x2DE0, end: 0x2DFF, name: "Cyrillic Extended-A", wiki: "https://en.wikipedia.org//wiki/Cyrillic_Extended-A", color: "#f7532f"},
    { start: 0x2E00, end: 0x2E7F, name: "Supplemental Punctuation", wiki: "https://en.wikipedia.org//wiki/Supplemental_Punctuation", color: "#77ee2e"},
    { start: 0x2E80, end: 0x2EFF, name: "CJK Radicals Supplement", wiki: "https://en.wikipedia.org//wiki/CJK_Radicals_Supplement", color: "#235806"},
    { start: 0x2F00, end: 0x2FDF, name: "Kangxi Radicals", wiki: "https://en.wikipedia.org//wiki/Kangxi_Radicals_(Unicode_block)", color: "#20d1d1"},
    { start: 0x2FF0, end: 0x2FFF, name: "Ideographic Description Characters", wiki: "https://en.wikipedia.org//wiki/Ideographic_Description_Characters_(Unicode_block)", color: "#2469d2"},
    { start: 0x3000, end: 0x303F, name: "CJK Symbols and Punctuation", wiki: "https://en.wikipedia.org//wiki/CJK_Symbols_and_Punctuation", color: "#fc9a80"},
    { start: 0x3040, end: 0x309F, name: "Hiragana", wiki: "https://en.wikipedia.org//wiki/Hiragana_(Unicode_block)", color: "#b255e4"},
    { start: 0x30A0, end: 0x30FF, name: "Katakana", wiki: "https://en.wikipedia.org//wiki/Katakana_(Unicode_block)", color: "#e6ce2d"},
    { start: 0x3100, end: 0x312F, name: "Bopomofo", wiki: "https://en.wikipedia.org//wiki/Bopomofo_(Unicode_block)", color: "#8a6a5b"},
    { start: 0x3130, end: 0x318F, name: "Hangul Compatibility Jamo", wiki: "https://en.wikipedia.org//wiki/Hangul_Compatibility_Jamo", color: "#9d779f"},
    { start: 0x3190, end: 0x319F, name: "Kanbun", wiki: "https://en.wikipedia.org//wiki/Kanbun_(Unicode_block)", color: "#e78485"},
    { start: 0x31A0, end: 0x31BF, name: "Bopomofo Extended", wiki: "https://en.wikipedia.org//wiki/Bopomofo_Extended", color: "#71dcca"},
    { start: 0x31C0, end: 0x31EF, name: "CJK Strokes", wiki: "https://en.wikipedia.org//wiki/CJK_Strokes_(Unicode_block)", color: "#0881ea"},
    { start: 0x31F0, end: 0x31FF, name: "Katakana Phonetic Extensions", wiki: "https://en.wikipedia.org//wiki/Katakana_Phonetic_Extensions", color: "#70cc42"},
    { start: 0x3200, end: 0x32FF, name: "Enclosed CJK Letters and Months", wiki: "https://en.wikipedia.org//wiki/Enclosed_CJK_Letters_and_Months", color: "#5564ad"},
    { start: 0x3300, end: 0x33FF, name: "CJK Compatibility", wiki: "https://en.wikipedia.org//wiki/CJK_Compatibility", color: "#50f587"},
    { start: 0x3400, end: 0x4DBF, name: "CJK Unified Ideographs Extension A", wiki: "https://en.wikipedia.org//wiki/CJK_Unified_Ideographs_Extension_A", color: "#d2a14e"},
    { start: 0x4DC0, end: 0x4DFF, name: "Yijing Hexagram Symbols", wiki: "https://en.wikipedia.org//wiki/Yijing_Hexagram_Symbols_(Unicode_block)", color: "#65b505"},
    { start: 0x4E00, end: 0x9FFF, name: "CJK Unified Ideographs", wiki: "https://en.wikipedia.org//wiki/CJK_Unified_Ideographs_(Unicode_block)", color: "#c3e612"},
    { start: 0xA000, end: 0xA48F, name: "Yi Syllables", wiki: "https://en.wikipedia.org//wiki/Yi_Syllables", color: "#a403db"},
    { start: 0xA490, end: 0xA4CF, name: "Yi Radicals", wiki: "https://en.wikipedia.org//wiki/Yi_Radicals", color: "#b4e35b"},
    { start: 0xA4D0, end: 0xA4FF, name: "Lisu", wiki: "https://en.wikipedia.org//wiki/Lisu_(Unicode_block)", color: "#3bc5db"},
    { start: 0xA500, end: 0xA63F, name: "Vai", wiki: "https://en.wikipedia.org//wiki/Vai_(Unicode_block)", color: "#2f2e62"},
    { start: 0xA640, end: 0xA69F, name: "Cyrillic Extended-B", wiki: "https://en.wikipedia.org//wiki/Cyrillic_Extended-B", color: "#9f4d60"},
    { start: 0xA6A0, end: 0xA6FF, name: "Bamum", wiki: "https://en.wikipedia.org//wiki/Bamum_(Unicode_block)", color: "#426ff5"},
    { start: 0xA700, end: 0xA71F, name: "Modifier Tone Letters", wiki: "https://en.wikipedia.org//wiki/Modifier_Tone_Letters", color: "#ba51a1"},
    { start: 0xA720, end: 0xA7FF, name: "Latin Extended-D", wiki: "https://en.wikipedia.org//wiki/Latin_Extended-D", color: "#760b53"},
    { start: 0xA800, end: 0xA82F, name: "Syloti Nagri", wiki: "https://en.wikipedia.org//wiki/Syloti_Nagri_(Unicode_block)", color: "#e76707"},
    { start: 0xA830, end: 0xA83F, name: "Common Indic Number Forms", wiki: "https://en.wikipedia.org//wiki/Common_Indic_Number_Forms", color: "#a1c026"},
    { start: 0xA840, end: 0xA87F, name: "Phags-pa", wiki: "https://en.wikipedia.org//wiki/Phags-pa_(Unicode_block)", color: "#a871d6"},
    { start: 0xA880, end: 0xA8DF, name: "Saurashtra", wiki: "https://en.wikipedia.org//wiki/Saurashtra_(Unicode_block)", color: "#c46f44"},
    { start: 0xA8E0, end: 0xA8FF, name: "Devanagari Extended", wiki: "https://en.wikipedia.org//wiki/Devanagari_Extended", color: "#a1040a"},
    { start: 0xA900, end: 0xA92F, name: "Kayah Li", wiki: "https://en.wikipedia.org//wiki/Kayah_Li_(Unicode_block)", color: "#ca357a"},
    { start: 0xA930, end: 0xA95F, name: "Rejang", wiki: "https://en.wikipedia.org//wiki/Rejang_(Unicode_block)", color: "#ac3126"},
    { start: 0xA960, end: 0xA97F, name: "Hangul Jamo Extended-A", wiki: "https://en.wikipedia.org//wiki/Hangul_Jamo_Extended-A", color: "#a19435"},
    { start: 0xA980, end: 0xA9DF, name: "Javanese", wiki: "https://en.wikipedia.org//wiki/Javanese_(Unicode_block)", color: "#33b39d"},
    { start: 0xA9E0, end: 0xA9FF, name: "Myanmar Extended-B", wiki: "https://en.wikipedia.org//wiki/Myanmar_Extended-B", color: "#91efe1"},
    { start: 0xAA00, end: 0xAA5F, name: "Cham", wiki: "https://en.wikipedia.org//wiki/Cham_(Unicode_block)", color: "#d6a2cd"},
    { start: 0xAA60, end: 0xAA7F, name: "Myanmar Extended-A", wiki: "https://en.wikipedia.org//wiki/Myanmar_Extended-A", color: "#a72eac"},
    { start: 0xAA80, end: 0xAADF, name: "Tai Viet", wiki: "https://en.wikipedia.org//wiki/Tai_Viet_(Unicode_block)", color: "#8986eb"},
    { start: 0xAAE0, end: 0xAAFF, name: "Meetei Mayek Extensions", wiki: "https://en.wikipedia.org//wiki/Meetei_Mayek_Extensions", color: "#d1c678"},
    { start: 0xAB00, end: 0xAB2F, name: "Ethiopic Extended-A", wiki: "https://en.wikipedia.org//wiki/Ethiopic_Extended-A", color: "#3558b0"},
    { start: 0xAB30, end: 0xAB6F, name: "Latin Extended-E", wiki: "https://en.wikipedia.org//wiki/Latin_Extended-E", color: "#7a5a20"},
    { start: 0xAB70, end: 0xABBF, name: "Cherokee Supplement", wiki: "https://en.wikipedia.org//wiki/Cherokee_Supplement", color: "#ce4cc2"},
    { start: 0xABC0, end: 0xABFF, name: "Meetei Mayek", wiki: "https://en.wikipedia.org//wiki/Meetei_Mayek_(Unicode_block)", color: "#140443"},
    { start: 0xAC00, end: 0xD7AF, name: "Hangul Syllables", wiki: "https://en.wikipedia.org//wiki/Hangul_Syllables", color: "#24ed7b"},
    { start: 0xD7B0, end: 0xD7FF, name: "Hangul Jamo Extended-B", wiki: "https://en.wikipedia.org//wiki/Hangul_Jamo_Extended-B", color: "#587359"},
    { start: 0xD800, end: 0xDB7F, name: "High Surrogates", wiki: "https://en.wikipedia.org//wiki/Universal_Character_Set_characters#Surrogates", color: "#daf6e9"},
    { start: 0xDB80, end: 0xDBFF, name: "High Private Use Surrogates", wiki: "https://en.wikipedia.org//wiki/Universal_Character_Set_characters#Surrogates", color: "#a5018f"},
    { start: 0xDC00, end: 0xDFFF, name: "Low Surrogates", wiki: "https://en.wikipedia.org//wiki/Universal_Character_Set_characters#Surrogates", color: "#892a2f"},
    { start: 0xE000, end: 0xF8FF, name: "Private Use Area", wiki: "https://en.wikipedia.org//wiki/Private_Use_Areas", color: "#10dcab"},
    { start: 0xF900, end: 0xFAFF, name: "CJK Compatibility Ideographs", wiki: "https://en.wikipedia.org//wiki/CJK_Compatibility_Ideographs", color: "#fe97a9"},
    { start: 0xFB00, end: 0xFB4F, name: "Alphabetic Presentation Forms", wiki: "https://en.wikipedia.org//wiki/Alphabetic_Presentation_Forms", color: "#f1a355"},
    { start: 0xFB50, end: 0xFDFF, name: "Arabic Presentation Forms-A", wiki: "https://en.wikipedia.org//wiki/Arabic_Presentation_Forms-A", color: "#d71ca0"},
    { start: 0xFE00, end: 0xFE0F, name: "Variation Selectors", wiki: "https://en.wikipedia.org//wiki/Variation_Selectors_(Unicode_block)", color: "#55a705"},
    { start: 0xFE10, end: 0xFE1F, name: "Vertical Forms", wiki: "https://en.wikipedia.org//wiki/Vertical_Forms", color: "#b2d31e"},
    { start: 0xFE20, end: 0xFE2F, name: "Combining Half Marks", wiki: "https://en.wikipedia.org//wiki/Combining_Half_Marks", color: "#24a04e"},
    { start: 0xFE30, end: 0xFE4F, name: "CJK Compatibility Forms", wiki: "https://en.wikipedia.org//wiki/CJK_Compatibility_Forms", color: "#ad4856"},
    { start: 0xFE50, end: 0xFE6F, name: "Small Form Variants", wiki: "https://en.wikipedia.org//wiki/Small_Form_Variants", color: "#41b61d"},
    { start: 0xFE70, end: 0xFEFF, name: "Arabic Presentation Forms-B", wiki: "https://en.wikipedia.org//wiki/Arabic_Presentation_Forms-B", color: "#dd8c3d"},
    { start: 0xFF00, end: 0xFFEF, name: "Halfwidth and Fullwidth Forms", wiki: "https://en.wikipedia.org//wiki/Halfwidth_and_Fullwidth_Forms_(Unicode_block)", color: "#a9e0c0"},
    { start: 0xFFF0, end: 0xFFFF, name: "Specials", wiki: "https://en.wikipedia.org//wiki/Specials_(Unicode_block)", color: "#2560fa"},
    { start: 0x10000, end: 0x1007F, name: "Linear B Syllabary", wiki: "https://en.wikipedia.org//wiki/Linear_B_Syllabary", color: "#c47e41"},
    { start: 0x10080, end: 0x100FF, name: "Linear B Ideograms", wiki: "https://en.wikipedia.org//wiki/Linear_B_Ideograms", color: "#a03ea8"},
    { start: 0x10100, end: 0x1013F, name: "Aegean Numbers", wiki: "https://en.wikipedia.org//wiki/Aegean_Numbers_(Unicode_block)", color: "#7235b3"},
    { start: 0x10140, end: 0x1018F, name: "Ancient Greek Numbers", wiki: "https://en.wikipedia.org//wiki/Ancient_Greek_Numbers_(Unicode_block)", color: "#a81a33"},
    { start: 0x10190, end: 0x101CF, name: "Ancient Symbols", wiki: "https://en.wikipedia.org//wiki/Ancient_Symbols_(Unicode_block)", color: "#1d458e"},
    { start: 0x101D0, end: 0x101FF, name: "Phaistos Disc", wiki: "https://en.wikipedia.org//wiki/Phaistos_Disc_(Unicode_block)", color: "#ff4557"},
    { start: 0x10280, end: 0x1029F, name: "Lycian", wiki: "https://en.wikipedia.org//wiki/Lycian_(Unicode_block)", color: "#e99e3d"},
    { start: 0x102A0, end: 0x102DF, name: "Carian", wiki: "https://en.wikipedia.org//wiki/Carian_(Unicode_block)", color: "#74f556"},
    { start: 0x102E0, end: 0x102FF, name: "Coptic Epact Numbers", wiki: "https://en.wikipedia.org//wiki/Coptic_Epact_Numbers", color: "#286f1c"},
    { start: 0x10300, end: 0x1032F, name: "Old Italic", wiki: "https://en.wikipedia.org//wiki/Old_Italic_(Unicode_block)", color: "#fd1738"},
    { start: 0x10330, end: 0x1034F, name: "Gothic", wiki: "https://en.wikipedia.org//wiki/Gothic_(Unicode_block)", color: "#ca02fb"},
    { start: 0x10350, end: 0x1037F, name: "Old Permic", wiki: "https://en.wikipedia.org//wiki/Old_Permic_(Unicode_block)", color: "#ce8f58"},
    { start: 0x10380, end: 0x1039F, name: "Ugaritic", wiki: "https://en.wikipedia.org//wiki/Ugaritic_(Unicode_block)", color: "#899037"},
    { start: 0x103A0, end: 0x103DF, name: "Old Persian", wiki: "https://en.wikipedia.org//wiki/Old_Persian_(Unicode_block)", color: "#701801"},
    { start: 0x10400, end: 0x1044F, name: "Deseret", wiki: "https://en.wikipedia.org//wiki/Deseret_(Unicode_block)", color: "#dcb564"},
    { start: 0x10450, end: 0x1047F, name: "Shavian", wiki: "https://en.wikipedia.org//wiki/Shavian_(Unicode_block)", color: "#a2502b"},
    { start: 0x10480, end: 0x104AF, name: "Osmanya", wiki: "https://en.wikipedia.org//wiki/Osmanya_(Unicode_block)", color: "#9fa910"},
    { start: 0x104B0, end: 0x104FF, name: "Osage", wiki: "https://en.wikipedia.org//wiki/Osage_(Unicode_block)", color: "#b22bf6"},
    { start: 0x10500, end: 0x1052F, name: "Elbasan", wiki: "https://en.wikipedia.org//wiki/Elbasan_(Unicode_block)", color: "#208d17"},
    { start: 0x10530, end: 0x1056F, name: "Caucasian Albanian", wiki: "https://en.wikipedia.org//wiki/Caucasian_Albanian_(Unicode_block)", color: "#7500dc"},
    { start: 0x10570, end: 0x105BF, name: "Vithkuqi", wiki: "https://en.wikipedia.org//wiki/Vithkuqi_(Unicode_block)", color: "#412c15"},
    { start: 0x10600, end: 0x1077F, name: "Linear A", wiki: "https://en.wikipedia.org//wiki/Linear_A_(Unicode_block)", color: "#bbca49"},
    { start: 0x10780, end: 0x107BF, name: "Latin Extended-F", wiki: "https://en.wikipedia.org//wiki/Latin_Extended-F", color: "#be517d"},
    { start: 0x10800, end: 0x1083F, name: "Cypriot Syllabary", wiki: "https://en.wikipedia.org//wiki/Cypriot_Syllabary_(Unicode_block)", color: "#99b2fc"},
    { start: 0x10840, end: 0x1085F, name: "Imperial Aramaic", wiki: "https://en.wikipedia.org//wiki/Imperial_Aramaic_(Unicode_block)", color: "#79e5aa"},
    { start: 0x10860, end: 0x1087F, name: "Palmyrene", wiki: "https://en.wikipedia.org//wiki/Palmyrene_(Unicode_block)", color: "#8d5723"},
    { start: 0x10880, end: 0x108AF, name: "Nabataean", wiki: "https://en.wikipedia.org//wiki/Nabataean_(Unicode_block)", color: "#26641a"},
    { start: 0x108E0, end: 0x108FF, name: "Hatran", wiki: "https://en.wikipedia.org//wiki/Hatran_(Unicode_block)", color: "#45b410"},
    { start: 0x10900, end: 0x1091F, name: "Phoenician", wiki: "https://en.wikipedia.org//wiki/Phoenician_(Unicode_block)", color: "#face43"},
    { start: 0x10920, end: 0x1093F, name: "Lydian", wiki: "https://en.wikipedia.org//wiki/Lydian_(Unicode_block)", color: "#12f981"},
    { start: 0x10980, end: 0x1099F, name: "Meroitic Hieroglyphs", wiki: "https://en.wikipedia.org//wiki/Meroitic_Hieroglyphs_(Unicode_block)", color: "#f17716"},
    { start: 0x109A0, end: 0x109FF, name: "Meroitic Cursive", wiki: "https://en.wikipedia.org//wiki/Meroitic_Cursive_(Unicode_block)", color: "#9157f9"},
    { start: 0x10A00, end: 0x10A5F, name: "Kharoshthi", wiki: "https://en.wikipedia.org//wiki/Kharoshthi_(Unicode_block)", color: "#5436e2"},
    { start: 0x10A60, end: 0x10A7F, name: "Old South Arabian", wiki: "https://en.wikipedia.org//wiki/Old_South_Arabian_(Unicode_block)", color: "#011598"},
    { start: 0x10A80, end: 0x10A9F, name: "Old North Arabian", wiki: "https://en.wikipedia.org//wiki/Old_North_Arabian_(Unicode_block)", color: "#6056af"},
    { start: 0x10AC0, end: 0x10AFF, name: "Manichaean", wiki: "https://en.wikipedia.org//wiki/Manichaean_(Unicode_block)", color: "#820c51"},
    { start: 0x10B00, end: 0x10B3F, name: "Avestan", wiki: "https://en.wikipedia.org//wiki/Avestan_(Unicode_block)", color: "#ba89ba"},
    { start: 0x10B40, end: 0x10B5F, name: "Inscriptional Parthian", wiki: "https://en.wikipedia.org//wiki/Inscriptional_Parthian_(Unicode_block)", color: "#bc0f71"},
    { start: 0x10B60, end: 0x10B7F, name: "Inscriptional Pahlavi", wiki: "https://en.wikipedia.org//wiki/Inscriptional_Pahlavi_(Unicode_block)", color: "#c17257"},
    { start: 0x10B80, end: 0x10BAF, name: "Psalter Pahlavi", wiki: "https://en.wikipedia.org//wiki/Psalter_Pahlavi_(Unicode_block)", color: "#e20fed"},
    { start: 0x10C00, end: 0x10C4F, name: "Old Turkic", wiki: "https://en.wikipedia.org//wiki/Old_Turkic_(Unicode_block)", color: "#46ada2"},
    { start: 0x10C80, end: 0x10CFF, name: "Old Hungarian", wiki: "https://en.wikipedia.org//wiki/Old_Hungarian_(Unicode_block)", color: "#11a2c8"},
    { start: 0x10D00, end: 0x10D3F, name: "Hanifi Rohingya", wiki: "https://en.wikipedia.org//wiki/Hanifi_Rohingya_(Unicode_block)", color: "#52cbc3"},
    { start: 0x10E60, end: 0x10E7F, name: "Rumi Numeral Symbols", wiki: "https://en.wikipedia.org//wiki/Rumi_Numeral_Symbols", color: "#a0cbdf"},
    { start: 0x10E80, end: 0x10EBF, name: "Yezidi", wiki: "https://en.wikipedia.org//wiki/Yezidi_(Unicode_block)", color: "#e33704"},
    { start: 0x10EC0, end: 0x10EFF, name: "Arabic Extended-C", wiki: "https://en.wikipedia.org//wiki/Arabic_Extended-C", color: "#c5a124"},
    { start: 0x10F00, end: 0x10F2F, name: "Old Sogdian", wiki: "https://en.wikipedia.org//wiki/Old_Sogdian_(Unicode_block)", color: "#078a67"},
    { start: 0x10F30, end: 0x10F6F, name: "Sogdian", wiki: "https://en.wikipedia.org//wiki/Sogdian_(Unicode_block)", color: "#1c5a9e"},
    { start: 0x10F70, end: 0x10FAF, name: "Old Uyghur", wiki: "https://en.wikipedia.org//wiki/Old_Uyghur_(Unicode_block)", color: "#136b87"},
    { start: 0x10FB0, end: 0x10FDF, name: "Chorasmian", wiki: "https://en.wikipedia.org//wiki/Chorasmian_(Unicode_block)", color: "#b0d43c"},
    { start: 0x10FE0, end: 0x10FFF, name: "Elymaic", wiki: "https://en.wikipedia.org//wiki/Elymaic_(Unicode_block)", color: "#250559"},
    { start: 0x11000, end: 0x1107F, name: "Brahmi", wiki: "https://en.wikipedia.org//wiki/Brahmi_(Unicode_block)", color: "#cb99df"},
    { start: 0x11080, end: 0x110CF, name: "Kaithi", wiki: "https://en.wikipedia.org//wiki/Kaithi_(Unicode_block)", color: "#259e89"},
    { start: 0x110D0, end: 0x110FF, name: "Sora Sompeng", wiki: "https://en.wikipedia.org//wiki/Sora_Sompeng_(Unicode_block)", color: "#bb0c61"},
    { start: 0x11100, end: 0x1114F, name: "Chakma", wiki: "https://en.wikipedia.org//wiki/Chakma_(Unicode_block)", color: "#62d736"},
    { start: 0x11150, end: 0x1117F, name: "Mahajani", wiki: "https://en.wikipedia.org//wiki/Mahajani_(Unicode_block)", color: "#7c9326"},
    { start: 0x11180, end: 0x111DF, name: "Sharada", wiki: "https://en.wikipedia.org//wiki/Sharada_(Unicode_block)", color: "#1c56c2"},
    { start: 0x111E0, end: 0x111FF, name: "Sinhala Archaic Numbers", wiki: "https://en.wikipedia.org//wiki/Sinhala_Archaic_Numbers", color: "#9dbaf2"},
    { start: 0x11200, end: 0x1124F, name: "Khojki", wiki: "https://en.wikipedia.org//wiki/Khojki_(Unicode_block)", color: "#f6e8b0"},
    { start: 0x11280, end: 0x112AF, name: "Multani", wiki: "https://en.wikipedia.org//wiki/Multani_(Unicode_block)", color: "#06d2f5"},
    { start: 0x112B0, end: 0x112FF, name: "Khudawadi", wiki: "https://en.wikipedia.org//wiki/Khudawadi_(Unicode_block)", color: "#9055fd"},
    { start: 0x11300, end: 0x1137F, name: "Grantha", wiki: "https://en.wikipedia.org//wiki/Grantha_(Unicode_block)", color: "#e7cc9f"},
    { start: 0x11400, end: 0x1147F, name: "Newa", wiki: "https://en.wikipedia.org//wiki/Newa_(Unicode_block)", color: "#8b0643"},
    { start: 0x11480, end: 0x114DF, name: "Tirhuta", wiki: "https://en.wikipedia.org//wiki/Tirhuta_(Unicode_block)", color: "#9133b7"},
    { start: 0x11580, end: 0x115FF, name: "Siddham", wiki: "https://en.wikipedia.org//wiki/Siddham_(Unicode_block)", color: "#f69ba5"},
    { start: 0x11600, end: 0x1165F, name: "Modi", wiki: "https://en.wikipedia.org//wiki/Modi_(Unicode_block)", color: "#36cb7a"},
    { start: 0x11660, end: 0x1167F, name: "Mongolian Supplement", wiki: "https://en.wikipedia.org//wiki/Mongolian_Supplement", color: "#400f5b"},
    { start: 0x11680, end: 0x116CF, name: "Takri", wiki: "https://en.wikipedia.org//wiki/Takri_(Unicode_block)", color: "#514819"},
    { start: 0x11700, end: 0x1174F, name: "Ahom", wiki: "https://en.wikipedia.org//wiki/Ahom_(Unicode_block)", color: "#164b79"},
    { start: 0x11800, end: 0x1184F, name: "Dogra", wiki: "https://en.wikipedia.org//wiki/Dogra_(Unicode_block)", color: "#a8840a"},
    { start: 0x118A0, end: 0x118FF, name: "Warang Citi", wiki: "https://en.wikipedia.org//wiki/Warang_Citi_(Unicode_block)", color: "#b24fc3"},
    { start: 0x11900, end: 0x1195F, name: "Dives Akuru", wiki: "https://en.wikipedia.org//wiki/Dives_Akuru_(Unicode_block)", color: "#778e89"},
    { start: 0x119A0, end: 0x119FF, name: "Nandinagari", wiki: "https://en.wikipedia.org//wiki/Nandinagari_(Unicode_block)", color: "#84e526"},
    { start: 0x11A00, end: 0x11A4F, name: "Zanabazar Square", wiki: "https://en.wikipedia.org//wiki/Zanabazar_Square_(Unicode_block)", color: "#412349"},
    { start: 0x11A50, end: 0x11AAF, name: "Soyombo", wiki: "https://en.wikipedia.org//wiki/Soyombo_(Unicode_block)", color: "#4d11d3"},
    { start: 0x11AB0, end: 0x11ABF, name: "Unified Canadian Aboriginal Syllabics Extended-A", wiki: "https://en.wikipedia.org//wiki/Unified_Canadian_Aboriginal_Syllabics_Extended-A", color: "#02fce1"},
    { start: 0x11AC0, end: 0x11AFF, name: "Pau Cin Hau", wiki: "https://en.wikipedia.org//wiki/Pau_Cin_Hau_(Unicode_block)", color: "#5557a7"},
    { start: 0x11B00, end: 0x11B5F, name: "Devanagari Extended-A", wiki: "https://en.wikipedia.org//wiki/Devanagari_Extended-A", color: "#6c26d6"},
    { start: 0x11C00, end: 0x11C6F, name: "Bhaiksuki", wiki: "https://en.wikipedia.org//wiki/Bhaiksuki_(Unicode_block)", color: "#2dd266"},
    { start: 0x11C70, end: 0x11CBF, name: "Marchen", wiki: "https://en.wikipedia.org//wiki/Marchen_(Unicode_block)", color: "#fc9e47"},
    { start: 0x11D00, end: 0x11D5F, name: "Masaram Gondi", wiki: "https://en.wikipedia.org//wiki/Masaram_Gondi_(Unicode_block)", color: "#499f11"},
    { start: 0x11D60, end: 0x11DAF, name: "Gunjala Gondi", wiki: "https://en.wikipedia.org//wiki/Gunjala_Gondi_(Unicode_block)", color: "#035dc9"},
    { start: 0x11EE0, end: 0x11EFF, name: "Makasar", wiki: "https://en.wikipedia.org//wiki/Makasar_(Unicode_block)", color: "#64ea44"},
    { start: 0x11F00, end: 0x11F5F, name: "Kawi", wiki: "https://en.wikipedia.org//wiki/Kawi_(Unicode_block)", color: "#c8cbe1"},
    { start: 0x11FB0, end: 0x11FBF, name: "Lisu Supplement", wiki: "https://en.wikipedia.org//wiki/Lisu_Supplement", color: "#d0f611"},
    { start: 0x11FC0, end: 0x11FFF, name: "Tamil Supplement", wiki: "https://en.wikipedia.org//wiki/Tamil_Supplement", color: "#c2e1f3"},
    { start: 0x12000, end: 0x123FF, name: "Cuneiform", wiki: "https://en.wikipedia.org//wiki/Cuneiform_(Unicode_block)", color: "#a1f093"},
    { start: 0x12400, end: 0x1247F, name: "Cuneiform Numbers and Punctuation", wiki: "https://en.wikipedia.org//wiki/Cuneiform_Numbers_and_Punctuation", color: "#e5747b"},
    { start: 0x12480, end: 0x1254F, name: "Early Dynastic Cuneiform", wiki: "https://en.wikipedia.org//wiki/Early_Dynastic_Cuneiform_(Unicode_block)", color: "#d30c0f"},
    { start: 0x12F90, end: 0x12FFF, name: "Cypro-Minoan", wiki: "https://en.wikipedia.org//wiki/Cypro-Minoan_(Unicode_block)", color: "#1563ed"},
    { start: 0x13000, end: 0x1342F, name: "Egyptian Hieroglyphs", wiki: "https://en.wikipedia.org//wiki/Egyptian_Hieroglyphs_(Unicode_block)", color: "#c757c0"},
    { start: 0x13430, end: 0x1345F, name: "Egyptian Hieroglyph Format Controls", wiki: "https://en.wikipedia.org//wiki/Egyptian_Hieroglyph_Format_Controls", color: "#e31089"},
    { start: 0x14400, end: 0x1467F, name: "Anatolian Hieroglyphs", wiki: "https://en.wikipedia.org//wiki/Anatolian_Hieroglyphs_(Unicode_block)", color: "#0701af"},
    { start: 0x16800, end: 0x16A3F, name: "Bamum Supplement", wiki: "https://en.wikipedia.org//wiki/Bamum_Supplement", color: "#21c1c7"},
    { start: 0x16A40, end: 0x16A6F, name: "Mro", wiki: "https://en.wikipedia.org//wiki/Mro_(Unicode_block)", color: "#433a10"},
    { start: 0x16A70, end: 0x16ACF, name: "Tangsa", wiki: "https://en.wikipedia.org//wiki/Tangsa_(Unicode_block)", color: "#3b1833"},
    { start: 0x16AD0, end: 0x16AFF, name: "Bassa Vah", wiki: "https://en.wikipedia.org//wiki/Bassa_Vah_(Unicode_block)", color: "#ab5af1"},
    { start: 0x16B00, end: 0x16B8F, name: "Pahawh Hmong", wiki: "https://en.wikipedia.org//wiki/Pahawh_Hmong_(Unicode_block)", color: "#75dc78"},
    { start: 0x16E40, end: 0x16E9F, name: "Medefaidrin", wiki: "https://en.wikipedia.org//wiki/Medefaidrin_(Unicode_block)", color: "#ecf9d8"},
    { start: 0x16F00, end: 0x16F9F, name: "Miao", wiki: "https://en.wikipedia.org//wiki/Miao_(Unicode_block)", color: "#96a56d"},
    { start: 0x16FE0, end: 0x16FFF, name: "Ideographic Symbols and Punctuation", wiki: "https://en.wikipedia.org//wiki/Ideographic_Symbols_and_Punctuation", color: "#ee0635"},
    { start: 0x17000, end: 0x187FF, name: "Tangut", wiki: "https://en.wikipedia.org//wiki/Tangut_(Unicode_block)", color: "#998aa1"},
    { start: 0x18800, end: 0x18AFF, name: "Tangut Components", wiki: "https://en.wikipedia.org//wiki/Tangut_Components", color: "#8c9a3a"},
    { start: 0x18B00, end: 0x18CFF, name: "Khitan Small Script", wiki: "https://en.wikipedia.org//wiki/Khitan_Small_Script_(Unicode_block)", color: "#6c39c0"},
    { start: 0x18D00, end: 0x18D7F, name: "Tangut Supplement", wiki: "https://en.wikipedia.org//wiki/Tangut_Supplement", color: "#ceca2f"},
    { start: 0x1AFF0, end: 0x1AFFF, name: "Kana Extended-B", wiki: "https://en.wikipedia.org//wiki/Kana_Extended-B", color: "#108e97"},
    { start: 0x1B000, end: 0x1B0FF, name: "Kana Supplement", wiki: "https://en.wikipedia.org//wiki/Kana_Supplement", color: "#311378"},
    { start: 0x1B100, end: 0x1B12F, name: "Kana Extended-A", wiki: "https://en.wikipedia.org//wiki/Kana_Extended-A", color: "#b2de0a"},
    { start: 0x1B130, end: 0x1B16F, name: "Small Kana Extension", wiki: "https://en.wikipedia.org//wiki/Small_Kana_Extension", color: "#b6f839"},
    { start: 0x1B170, end: 0x1B2FF, name: "Nushu", wiki: "https://en.wikipedia.org//wiki/Nushu_(Unicode_block)", color: "#53c81c"},
    { start: 0x1BC00, end: 0x1BC9F, name: "Duployan", wiki: "https://en.wikipedia.org//wiki/Duployan_(Unicode_block)", color: "#1736f5"},
    { start: 0x1BCA0, end: 0x1BCAF, name: "Shorthand Format Controls", wiki: "https://en.wikipedia.org//wiki/Shorthand_Format_Controls", color: "#f8dbee"},
    { start: 0x1CF00, end: 0x1CFCF, name: "Znamenny Musical Notation", wiki: "https://en.wikipedia.org//wiki/Znamenny_Musical_Notation", color: "#33a1ce"},
    { start: 0x1D000, end: 0x1D0FF, name: "Byzantine Musical Symbols", wiki: "https://en.wikipedia.org//wiki/Byzantine_Musical_Symbols", color: "#cbae28"},
    { start: 0x1D100, end: 0x1D1FF, name: "Musical Symbols", wiki: "https://en.wikipedia.org//wiki/Musical_Symbols_(Unicode_block)", color: "#0283d4"},
    { start: 0x1D200, end: 0x1D24F, name: "Ancient Greek Musical Notation", wiki: "https://en.wikipedia.org//wiki/Ancient_Greek_Musical_Notation", color: "#082804"},
    { start: 0x1D2C0, end: 0x1D2DF, name: "Kaktovik Numerals", wiki: "https://en.wikipedia.org//wiki/Kaktovik_Numerals_(Unicode_block)", color: "#a75a7f"},
    { start: 0x1D2E0, end: 0x1D2FF, name: "Mayan Numerals", wiki: "https://en.wikipedia.org//wiki/Mayan_Numerals_(Unicode_block)", color: "#a7a89f"},
    { start: 0x1D300, end: 0x1D35F, name: "Tai Xuan Jing Symbols", wiki: "https://en.wikipedia.org//wiki/Taixuanjing", color: "#7b6763"},
    { start: 0x1D360, end: 0x1D37F, name: "Counting Rod Numerals", wiki: "https://en.wikipedia.org//wiki/Counting_Rod_Numerals_(Unicode_block)", color: "#9af16d"},
    { start: 0x1D400, end: 0x1D7FF, name: "Mathematical Alphanumeric Symbols", wiki: "https://en.wikipedia.org//wiki/Mathematical_Alphanumeric_Symbols", color: "#c8aa3f"},
    { start: 0x1D800, end: 0x1DAAF, name: "Sutton SignWriting", wiki: "https://en.wikipedia.org//wiki/Sutton_SignWriting_(Unicode_block)", color: "#603d2d"},
    { start: 0x1DF00, end: 0x1DFFF, name: "Latin Extended-G", wiki: "https://en.wikipedia.org//wiki/Latin_Extended-G", color: "#62cf52"},
    { start: 0x1E000, end: 0x1E02F, name: "Glagolitic Supplement", wiki: "https://en.wikipedia.org//wiki/Glagolitic_Supplement", color: "#631f19"},
    { start: 0x1E030, end: 0x1E08F, name: "Cyrillic Extended-D", wiki: "https://en.wikipedia.org//wiki/Cyrillic_Extended-D", color: "#22b94e"},
    { start: 0x1E100, end: 0x1E14F, name: "Nyiakeng Puachue Hmong", wiki: "https://en.wikipedia.org//wiki/Nyiakeng_Puachue_Hmong_(Unicode_block)", color: "#31a284"},
    { start: 0x1E290, end: 0x1E2BF, name: "Toto", wiki: "https://en.wikipedia.org//wiki/Toto_(Unicode_block)", color: "#ac6588"},
    { start: 0x1E2C0, end: 0x1E2FF, name: "Wancho", wiki: "https://en.wikipedia.org//wiki/Wancho_(Unicode_block)", color: "#f9e93e"},
    { start: 0x1E4D0, end: 0x1E4FF, name: "Nag Mundari", wiki: "https://en.wikipedia.org//wiki/Nag_Mundari_(Unicode_block)", color: "#c76a6e"},
    { start: 0x1E7E0, end: 0x1E7FF, name: "Ethiopic Extended-B", wiki: "https://en.wikipedia.org//wiki/Ethiopic_Extended-B", color: "#cb3542"},
    { start: 0x1E800, end: 0x1E8DF, name: "Mende Kikakui", wiki: "https://en.wikipedia.org//wiki/Mende_Kikakui_(Unicode_block)", color: "#425b13"},
    { start: 0x1E900, end: 0x1E95F, name: "Adlam", wiki: "https://en.wikipedia.org//wiki/Adlam_(Unicode_block)", color: "#224f4f"},
    { start: 0x1EC70, end: 0x1ECBF, name: "Indic Siyaq Numbers", wiki: "https://en.wikipedia.org//wiki/Indic_Siyaq_Numbers", color: "#555c97"},
    { start: 0x1ED00, end: 0x1ED4F, name: "Ottoman Siyaq Numbers", wiki: "https://en.wikipedia.org//wiki/Ottoman_Siyaq_Numbers", color: "#67d402"},
    { start: 0x1EE00, end: 0x1EEFF, name: "Arabic Mathematical Alphabetic Symbols", wiki: "https://en.wikipedia.org//wiki/Arabic_Mathematical_Alphabetic_Symbols", color: "#274790"},
    { start: 0x1F000, end: 0x1F02F, name: "Mahjong Tiles", wiki: "https://en.wikipedia.org//wiki/Mahjong_Tiles_(Unicode_block)", color: "#2741a2"},
    { start: 0x1F030, end: 0x1F09F, name: "Domino Tiles", wiki: "https://en.wikipedia.org//wiki/Domino_Tiles", color: "#637734"},
    { start: 0x1F0A0, end: 0x1F0FF, name: "Playing Cards", wiki: "https://en.wikipedia.org//wiki/Playing_cards_in_Unicode", color: "#4eba37"},
    { start: 0x1F100, end: 0x1F1FF, name: "Enclosed Alphanumeric Supplement", wiki: "https://en.wikipedia.org//wiki/Enclosed_Alphanumeric_Supplement", color: "#240a49"},
    { start: 0x1F200, end: 0x1F2FF, name: "Enclosed Ideographic Supplement", wiki: "https://en.wikipedia.org//wiki/Enclosed_Ideographic_Supplement", color: "#9b043c"},
    { start: 0x1F300, end: 0x1F5FF, name: "Miscellaneous Symbols and Pictographs", wiki: "https://en.wikipedia.org//wiki/Miscellaneous_Symbols_and_Pictographs", color: "#b6c6bf"},
    { start: 0x1F600, end: 0x1F64F, name: "Emoticons", wiki: "https://en.wikipedia.org//wiki/Emoticons_(Unicode_block)", color: "#ccecd3"},
    { start: 0x1F650, end: 0x1F67F, name: "Ornamental Dingbats", wiki: "https://en.wikipedia.org//wiki/Ornamental_Dingbats", color: "#558d71"},
    { start: 0x1F680, end: 0x1F6FF, name: "Transport and Map Symbols", wiki: "https://en.wikipedia.org//wiki/Transport_and_Map_Symbols", color: "#a4b5f4"},
    { start: 0x1F700, end: 0x1F77F, name: "Alchemical Symbols", wiki: "https://en.wikipedia.org//wiki/Alchemical_Symbols_(Unicode_block)", color: "#c2f12c"},
    { start: 0x1F780, end: 0x1F7FF, name: "Geometric Shapes Extended", wiki: "https://en.wikipedia.org//wiki/Geometric_Shapes_Extended", color: "#221811"},
    { start: 0x1F800, end: 0x1F8FF, name: "Supplemental Arrows-C", wiki: "https://en.wikipedia.org//wiki/Supplemental_Arrows-C", color: "#12b7f1"},
    { start: 0x1F900, end: 0x1F9FF, name: "Supplemental Symbols and Pictographs", wiki: "https://en.wikipedia.org//wiki/Supplemental_Symbols_and_Pictographs", color: "#249ea3"},
    { start: 0x1FA00, end: 0x1FA6F, name: "Chess Symbols", wiki: "https://en.wikipedia.org//wiki/Chess_Symbols", color: "#0002e5"},
    { start: 0x1FA70, end: 0x1FAFF, name: "Symbols and Pictographs Extended-A", wiki: "https://en.wikipedia.org//wiki/Symbols_and_Pictographs_Extended-A", color: "#5b29fe"},
    { start: 0x1FB00, end: 0x1FBFF, name: "Symbols for Legacy Computing", wiki: "https://en.wikipedia.org//wiki/Symbols_for_Legacy_Computing", color: "#81f8a0"},
    { start: 0x20000, end: 0x2A6DF, name: "CJK Unified Ideographs Extension B", wiki: "https://en.wikipedia.org//wiki/CJK_Unified_Ideographs_Extension_B", color: "#a2b87a"},
    { start: 0x2A700, end: 0x2B73F, name: "CJK Unified Ideographs Extension C", wiki: "https://en.wikipedia.org//wiki/CJK_Unified_Ideographs_Extension_C", color: "#d3a63c"},
    { start: 0x2B740, end: 0x2B81F, name: "CJK Unified Ideographs Extension D", wiki: "https://en.wikipedia.org//wiki/CJK_Unified_Ideographs_Extension_D", color: "#8d4d22"},
    { start: 0x2B820, end: 0x2CEAF, name: "CJK Unified Ideographs Extension E", wiki: "https://en.wikipedia.org//wiki/CJK_Unified_Ideographs_Extension_E", color: "#01e6e5"},
    { start: 0x2CEB0, end: 0x2EBEF, name: "CJK Unified Ideographs Extension F", wiki: "https://en.wikipedia.org//wiki/CJK_Unified_Ideographs_Extension_F", color: "#7c3db9"},
    { start: 0x2F800, end: 0x2FA1F, name: "CJK Compatibility Ideographs Supplement", wiki: "https://en.wikipedia.org//wiki/CJK_Compatibility_Ideographs_Supplement", color: "#0f28fa"},
    { start: 0x30000, end: 0x3134F, name: "CJK Unified Ideographs Extension G", wiki: "https://en.wikipedia.org//wiki/CJK_Unified_Ideographs_Extension_G", color: "#2918e0"},
    { start: 0x31350, end: 0x323AF, name: "CJK Unified Ideographs Extension H", wiki: "https://en.wikipedia.org//wiki/CJK_Unified_Ideographs_Extension_H", color: "#c92a25"},
    { start: 0xE0000, end: 0xE007F, name: "Tags", wiki: "https://en.wikipedia.org//wiki/Tags_(Unicode_block)", color: "#35ecc3"},
    { start: 0xE0100, end: 0xE01EF, name: "Variation Selectors Supplement", wiki: "https://en.wikipedia.org//wiki/Variation_Selectors_Supplement", color: "#510c97"},
    { start: 0xF0000, end: 0xFFFFF, name: "Supplementary Private Use Area-A", wiki: "https://en.wikipedia.org//wiki/Private_Use_Areas", color: "#453e6f"},
    { start: 0x100000, end: 0x10FFFF, name: "Supplementary Private Use Area-B", wiki: "https://en.wikipedia.org//wiki/Private_Use_Areas", color: "#4e6efa"},
]

// Get unicdoe block for a character using binary search
export function getUnicodeBlock(char: string): UnicodeBlock {
    const code = getUnicodePoint(char);
    let start = 0
    let end = unicodeBlocks.length - 1
    while (start <= end) {
        const mid = Math.floor((start + end) / 2)
        const block = unicodeBlocks[mid]
        if (code < block.start) {
            end = mid - 1
        } else if (code > block.end) {
            start = mid + 1
        } else {
            return block
        }
    }
    return undefinedUnicodeBlock;
}

// Get unicode code point for a character
export function getUnicodePoint(char: string): number {
    return char.charCodeAt(0)
}

const hashCode = (str: string) => {
    let hash = 0
    for (let i = 0; i < str.length; i++) {
        hash = str.charCodeAt(i) + ((hash << 5) - hash)
    }
    return hash
}

