import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import TextareaAutosize from "react-textarea-autosize";
import { getUnicodeBlock } from "../utils/unicode";

const Home: NextPage = () => {
  const [value, setValue] = useState<string>("Пpивiт!");

  return (
    <div>
      <Head>
        <title>Character Detector</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gray-100  min-h-screen">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-3xl space-y-5 pt-3">
            <TextareaAutosize
              className="shadow-sm rounded p-2 w-full resize-none font-mono"
              value={value}
              minRows={5}
              onChange={(e) => setValue(e.target.value)}
            />
            <div className="shadow-sm rounded p-2 w-full bg-white grid gap-[2px] grid-cols-[repeat(auto\-fill,2.5rem)]">
              {value.split("").map((char, index) => {
                const block = getUnicodeBlock(char);
                const color = block?.color ?? "bg-slate-50";
                return (
                  <div
                    className="rounded w-10 h-10 flex items-center justify-center border-[1px] text-white cursor-default"
                    style={{
                      backgroundColor: color,
                    }}
                    key={index}
                    title={block?.name ?? "Unknown"}
                  >
                    {char}
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
